//! The raw bindings generated by `bindgen`.
#![allow(dead_code, nonstandard_style)]
// Bindgen generates funny tests - https://github.com/rust-lang/rust-bindgen/issues/1651
#![allow(deref_nullptr)]

include!(concat!(env!("OUT_DIR"), "/", "bindings.rs"));
